// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfx68k.h for the primary calling header

#include "Vfx68k_fx68k_bmux_1840.h"
#include "Vfx68k__Syms.h"


//--------------------
// STATIC VARIABLES


//--------------------

VL_CTOR_IMP(Vfx68k_fx68k_bmux_1840) {
    // Reset internal values
    // Reset structure values
    _ctor_var_reset();
}

void Vfx68k_fx68k_bmux_1840::__Vconfigure(Vfx68k__Syms* vlSymsp, bool first) {
    if (0 && first) {}  // Prevent unused
    this->__VlSymsp = vlSymsp;
}

Vfx68k_fx68k_bmux_1840::~Vfx68k_fx68k_bmux_1840() {
}

//--------------------
// Internal Methods

VL_INLINE_OPT void Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8__1(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8__1\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    this->z = ((0x80000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
				 << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
			       | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
				   << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
	       | ((0x40000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
				    << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
				  | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
				      << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
		  | ((0x20000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
				       << 0x1dU) & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
				     | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
					 << 0x1dU) 
					& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
		     | ((0x10000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
					  << 0x1cU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
					| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
					    << 0x1cU) 
					   & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
			| ((0x8000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
					    << 0x1bU) 
					   & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
					  | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
					      << 0x1bU) 
					     & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
			   | ((0x4000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
					       << 0x1aU) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
					     | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
						 << 0x1aU) 
						& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
			      | ((0x2000000U & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
						  << 0x19U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
						| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
						    << 0x19U) 
						   & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
				 | ((0x1000000U & (
						   (((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
						     << 0x18U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
						   | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
						       << 0x18U) 
						      & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
				    | ((0x800000U & 
					((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
					   << 0x17U) 
					  & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
					 | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
					     << 0x17U) 
					    & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
				       | ((0x400000U 
					   & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
						<< 0x16U) 
					       & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
					      | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
						  << 0x16U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
					  | ((0x200000U 
					      & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
						   << 0x15U) 
						  & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
						 | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
						     << 0x15U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
					     | ((0x100000U 
						 & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
						      << 0x14U) 
						     & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
						    | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
							<< 0x14U) 
						       & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
						| ((0x80000U 
						    & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
							 << 0x13U) 
							& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
						       | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
							   << 0x13U) 
							  & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
						   | ((0x40000U 
						       & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
							    << 0x12U) 
							   & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
							  | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
							      << 0x12U) 
							     & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
						      | ((0x20000U 
							  & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
							       << 0x11U) 
							      & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
							     | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
								 << 0x11U) 
								& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
							 | ((0x10000U 
							     & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
								  << 0x10U) 
								 & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
								| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
								    << 0x10U) 
								   & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
							    | ((0x8000U 
								& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
								     << 0xfU) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
								   | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
								       << 0xfU) 
								      & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
							       | ((0x4000U 
								   & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
									<< 0xeU) 
								       & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
								      | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
									  << 0xeU) 
									 & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
								  | ((0x2000U 
								      & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
									   << 0xdU) 
									  & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
									 | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
									     << 0xdU) 
									    & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
								     | ((0x1000U 
									 & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
									      << 0xcU) 
									     & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
									    | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 0xcU) 
									       & vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
									| ((0x800U 
									    & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
									       | (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
									   | ((0x400U 
									       & ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
									      | ((0x200U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((0x100U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((0x80U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((0x40U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((0x20U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((0x10U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((8U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((4U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| ((2U 
										& ((((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| (((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))) 
										| (1U 
										& (((IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_0) 
										| ((~ (IData)(vlTOPp->fx68k__DOT__nDecoder__DOT__n_484)) 
										& vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_aob_1442_8__in_1))))))))))))))))))))))))))))))))));
}

VL_INLINE_OPT void Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_aob_1439_12__3(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_aob_1439_12__3\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Variables
    // Begin mtask footprint  all: 
    VL_SIG(__Vtemp1,31,0);
    // Body
    __Vtemp1 = ((0x80000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
				  << 0x1fU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
				    << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
		| ((0x40000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
				     << 0x1eU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
				       << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
		   | ((0x20000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
					<< 0x1dU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
					  << 0x1dU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
		      | ((0x10000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
					   << 0x1cU) 
					  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
					     << 0x1cU) 
					    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
			 | ((0x8000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
					     << 0x1bU) 
					    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
					       << 0x1bU) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
			    | ((0x4000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
						<< 0x1aU) 
					       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
						  << 0x1aU) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
			       | ((0x2000000U & (((
						   (~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
						   << 0x19U) 
						  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
						     << 0x19U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
				  | ((0x1000000U & 
				      ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
					 << 0x18U) 
					& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
					   << 0x18U) 
					  & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
				     | ((0x800000U 
					 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
					      << 0x17U) 
					     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
						<< 0x17U) 
					       & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
					| ((0x400000U 
					    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
						 << 0x16U) 
						& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
						   << 0x16U) 
						  & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
					   | ((0x200000U 
					       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
						    << 0x15U) 
						   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
						      << 0x15U) 
						     & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
					      | ((0x100000U 
						  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
						       << 0x14U) 
						      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
						     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
							 << 0x14U) 
							& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
						 | ((0x80000U 
						     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
							  << 0x13U) 
							 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
							| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
							    << 0x13U) 
							   & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
						    | ((0x40000U 
							& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
							     << 0x12U) 
							    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
							   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
							       << 0x12U) 
							      & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
						       | ((0x20000U 
							   & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
								<< 0x11U) 
							       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
							      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
								  << 0x11U) 
								 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
							  | ((0x10000U 
							      & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
								   << 0x10U) 
								  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
								 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
								     << 0x10U) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
							     | ((0x8000U 
								 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
								      << 0xfU) 
								     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
								    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
									<< 0xfU) 
								       & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
								| ((0x4000U 
								    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
									 << 0xeU) 
									& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
								       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
									   << 0xeU) 
									  & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
								   | ((0x2000U 
								       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
									    << 0xdU) 
									   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
									  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
									      << 0xdU) 
									     & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
								      | ((0x1000U 
									  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
									       << 0xcU) 
									      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
									     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 0xcU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
									 | ((0x800U 
									     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 0xbU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
									    | ((0x400U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 0xaU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
									       | ((0x200U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 9U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((0x100U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 8U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((0x80U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 7U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((0x40U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 6U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((0x20U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 5U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((0x10U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 4U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((8U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 3U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((4U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 2U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| ((2U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										<< 1U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
										| (1U 
										& (((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451)) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_aob_1442_8.z) 
										| ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__n_451) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__auReg))))))))))))))))))))))))))))))))));
    this->z = __Vtemp1;
}

VL_INLINE_OPT void Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12__2(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12__2\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    this->z = ((0x80000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
				 << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
			       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
				   << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
	       | ((0x40000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
				    << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
				  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
				      << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
		  | ((0x20000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
				       << 0x1dU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
				     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
					 << 0x1dU) 
					& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
		     | ((0x10000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
					  << 0x1cU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
					| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
					    << 0x1cU) 
					   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
			| ((0x8000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
					    << 0x1bU) 
					   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
					  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
					      << 0x1bU) 
					     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
			   | ((0x4000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
					       << 0x1aU) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
						 << 0x1aU) 
						& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
			      | ((0x2000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
						  << 0x19U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
						    << 0x19U) 
						   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
				 | ((0x1000000U & (
						   (((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
						     << 0x18U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
						   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
						       << 0x18U) 
						      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
				    | ((0x800000U & 
					((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
					   << 0x17U) 
					  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
					     << 0x17U) 
					    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
				       | ((0x400000U 
					   & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
						<< 0x16U) 
					       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
						  << 0x16U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
					  | ((0x200000U 
					      & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
						   << 0x15U) 
						  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
						     << 0x15U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
					     | ((0x100000U 
						 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
						      << 0x14U) 
						     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
						    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
							<< 0x14U) 
						       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
						| ((0x80000U 
						    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
							 << 0x13U) 
							& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
						       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
							   << 0x13U) 
							  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
						   | ((0x40000U 
						       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
							    << 0x12U) 
							   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
							  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
							      << 0x12U) 
							     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
						      | ((0x20000U 
							  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
							       << 0x11U) 
							      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
							     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
								 << 0x11U) 
								& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
							 | ((0x10000U 
							     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
								  << 0x10U) 
								 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
								| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
								    << 0x10U) 
								   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
							    | ((0x8000U 
								& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
								     << 0xfU) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
								   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
								       << 0xfU) 
								      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
							       | ((0x4000U 
								   & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
									<< 0xeU) 
								       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
								      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
									  << 0xeU) 
									 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
								  | ((0x2000U 
								      & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
									   << 0xdU) 
									  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
									 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
									     << 0xdU) 
									    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
								     | ((0x1000U 
									 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
									      << 0xcU) 
									     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
									    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 0xcU) 
									       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
									| ((0x800U 
									    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
									       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
									   | ((0x400U 
									       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
									      | ((0x200U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((0x100U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((0x80U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((0x40U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((0x20U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((0x10U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((8U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((4U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| ((2U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))) 
										| (1U 
										& (((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift)) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_0) 
										| ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__cmbsop_isShift) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_516_12__in_1))))))))))))))))))))))))))))))))));
}

VL_INLINE_OPT void Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12__4(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12__4\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Variables
    // Begin mtask footprint  all: 
    VL_SIG(__Vtemp2,31,0);
    // Body
    __Vtemp2 = ((0x80000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
				  << 0x1fU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
				    << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
		| ((0x40000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
				     << 0x1eU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
				       << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
		   | ((0x20000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
					<< 0x1dU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
					  << 0x1dU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
		      | ((0x10000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
					   << 0x1cU) 
					  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
					     << 0x1cU) 
					    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
			 | ((0x8000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
					     << 0x1bU) 
					    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
					       << 0x1bU) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
			    | ((0x4000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
						<< 0x1aU) 
					       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
						  << 0x1aU) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
			       | ((0x2000000U & (((
						   (~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
						   << 0x19U) 
						  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
						     << 0x19U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
				  | ((0x1000000U & 
				      ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
					 << 0x18U) 
					& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
					   << 0x18U) 
					  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
				     | ((0x800000U 
					 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
					      << 0x17U) 
					     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
						<< 0x17U) 
					       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
					| ((0x400000U 
					    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
						 << 0x16U) 
						& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
						   << 0x16U) 
						  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
					   | ((0x200000U 
					       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
						    << 0x15U) 
						   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
						      << 0x15U) 
						     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
					      | ((0x100000U 
						  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
						       << 0x14U) 
						      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
						     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
							 << 0x14U) 
							& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
						 | ((0x80000U 
						     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
							  << 0x13U) 
							 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
							| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
							    << 0x13U) 
							   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
						    | ((0x40000U 
							& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
							     << 0x12U) 
							    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
							   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
							       << 0x12U) 
							      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
						       | ((0x20000U 
							   & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
								<< 0x11U) 
							       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
							      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
								  << 0x11U) 
								 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
							  | ((0x10000U 
							      & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
								   << 0x10U) 
								  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
								 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
								     << 0x10U) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
							     | ((0x8000U 
								 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
								      << 0xfU) 
								     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
								    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
									<< 0xfU) 
								       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
								| ((0x4000U 
								    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
									 << 0xeU) 
									& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
								       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
									   << 0xeU) 
									  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
								   | ((0x2000U 
								       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
									    << 0xdU) 
									   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
									  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
									      << 0xdU) 
									     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
								      | ((0x1000U 
									  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
									       << 0xcU) 
									      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
									     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 0xcU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
									 | ((0x800U 
									     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 0xbU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
									    | ((0x400U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 0xaU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
									       | ((0x200U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 9U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((0x100U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 8U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((0x80U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 7U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((0x40U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 6U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((0x20U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 5U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((0x10U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 4U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((8U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 3U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((4U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 2U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| ((2U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										<< 1U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))) 
										| (1U 
										& (((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404)) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_516_12.z) 
										| ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__n_404) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_513_12__in_1))))))))))))))))))))))))))))))))));
    this->z = __Vtemp2;
}

VL_INLINE_OPT void Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17__5(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17__5\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Variables
    // Begin mtask footprint  all: 
    VL_SIG(__Vtemp3,31,0);
    // Body
    __Vtemp3 = ((0x80000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
				  << 0x1fU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
				    << 0x1fU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
		| ((0x40000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
				     << 0x1eU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
				       << 0x1eU) & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
		   | ((0x20000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
					<< 0x1dU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
					  << 0x1dU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
		      | ((0x10000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
					   << 0x1cU) 
					  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
					     << 0x1cU) 
					    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
			 | ((0x8000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
					     << 0x1bU) 
					    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
					       << 0x1bU) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
			    | ((0x4000000U & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
						<< 0x1aU) 
					       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
						  << 0x1aU) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
			       | ((0x2000000U & (((
						   (~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
						   << 0x19U) 
						  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
						     << 0x19U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
				  | ((0x1000000U & 
				      ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
					 << 0x18U) 
					& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
					   << 0x18U) 
					  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
				     | ((0x800000U 
					 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
					      << 0x17U) 
					     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
						<< 0x17U) 
					       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
					| ((0x400000U 
					    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
						 << 0x16U) 
						& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
						   << 0x16U) 
						  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
					   | ((0x200000U 
					       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
						    << 0x15U) 
						   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
						      << 0x15U) 
						     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
					      | ((0x100000U 
						  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
						       << 0x14U) 
						      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
						     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
							 << 0x14U) 
							& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
						 | ((0x80000U 
						     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
							  << 0x13U) 
							 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
							| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
							    << 0x13U) 
							   & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
						    | ((0x40000U 
							& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
							     << 0x12U) 
							    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
							   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
							       << 0x12U) 
							      & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
						       | ((0x20000U 
							   & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
								<< 0x11U) 
							       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
							      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
								  << 0x11U) 
								 & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
							  | ((0x10000U 
							      & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
								   << 0x10U) 
								  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
								 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
								     << 0x10U) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
							     | ((0x8000U 
								 & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
								      << 0xfU) 
								     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
								    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
									<< 0xfU) 
								       & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
								| ((0x4000U 
								    & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
									 << 0xeU) 
									& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
								       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
									   << 0xeU) 
									  & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
								   | ((0x2000U 
								       & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
									    << 0xdU) 
									   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
									  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
									      << 0xdU) 
									     & vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
								      | ((0x1000U 
									  & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
									       << 0xcU) 
									      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
									     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 0xcU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
									 | ((0x800U 
									     & ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 0xbU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 0xbU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
									    | ((0x400U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 0xaU) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 0xaU) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
									       | ((0x200U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 9U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 9U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((0x100U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 8U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 8U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((0x80U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 7U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 7U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((0x40U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 6U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 6U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((0x20U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 5U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 5U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((0x10U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 4U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 4U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((8U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 3U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 3U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((4U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 2U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 2U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| ((2U 
										& ((((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										<< 1U) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										<< 1U) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))) 
										| (1U 
										& (((~ (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1)) 
										& vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_513_12.z) 
										| ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__n_1) 
										& vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT____Vcellinp__mux_result_511_17__in_1))))))))))))))))))))))))))))))))));
    this->z = __Vtemp3;
}

void Vfx68k_fx68k_bmux_1840::_ctor_var_reset() {
    VL_DEBUG_IF(VL_DBG_MSGF("+              Vfx68k_fx68k_bmux_1840::_ctor_var_reset\n"); );
    // Body
    ctl = VL_RAND_RESET_I(1);
    in_0 = VL_RAND_RESET_I(32);
    in_1 = VL_RAND_RESET_I(32);
    z = VL_RAND_RESET_I(32);
}
