// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfx68k.h for the primary calling header

#include "Vfx68k_fx68k_mux_1906.h"
#include "Vfx68k__Syms.h"


//--------------------
// STATIC VARIABLES


//--------------------

VL_CTOR_IMP(Vfx68k_fx68k_mux_1906) {
    // Reset internal values
    // Reset structure values
    _ctor_var_reset();
}

void Vfx68k_fx68k_mux_1906::__Vconfigure(Vfx68k__Syms* vlSymsp, bool first) {
    if (0 && first) {}  // Prevent unused
    this->__VlSymsp = vlSymsp;
}

Vfx68k_fx68k_mux_1906::~Vfx68k_fx68k_mux_1906() {
}

//--------------------
// Internal Methods

VL_INLINE_OPT void Vfx68k_fx68k_mux_1906::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_ablMux_1346_10__1(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vfx68k_fx68k_mux_1906::_settle__TOP__fx68k__DOT__excUnit__DOT__mux_ablMux_1346_10__1\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    this->z = ((0x8000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				  << 9U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				    << 0xaU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
			       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				   << 0xbU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
			      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				  << 0xcU) & (IData)(vlTOPp->fx68k__DOT__ftu))) 
			     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				 << 0xdU) & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
			    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				<< 0xeU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
			   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
			       << 0xfU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
	       | ((0x4000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				     << 8U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				       << 9U) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
				  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				      << 0xaU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
				 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				     << 0xbU) & (IData)(vlTOPp->fx68k__DOT__ftu))) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				    << 0xcU) & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
			       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				   << 0xdU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
			      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				  << 0xeU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
		  | ((0x2000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					<< 7U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					  << 8U) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
				     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					 << 9U) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
				    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					<< 0xaU) & (IData)(vlTOPp->fx68k__DOT__ftu))) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				       << 0xbU) & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
				  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				      << 0xcU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
				 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
				     << 0xdU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
		     | ((0x1000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					   << 6U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					     << 7U) 
					    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
					| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					    << 8U) 
					   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					   << 9U) & (IData)(vlTOPp->fx68k__DOT__ftu))) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					  << 0xaU) 
					 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
				     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					 << 0xbU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
				    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					<< 0xcU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
			| ((0x800U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					     << 5U) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					       << 6U) 
					      & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
					  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					      << 7U) 
					     & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					     << 8U) 
					    & (IData)(vlTOPp->fx68k__DOT__ftu))) 
					| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					    << 9U) 
					   & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					   << 0xaU) 
					  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					  << 0xbU) 
					 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
			   | ((0x400U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						<< 4U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						  << 5U) 
						 & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						 << 6U) 
						& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						<< 7U) 
					       & (IData)(vlTOPp->fx68k__DOT__ftu))) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					       << 8U) 
					      & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
					  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					      << 9U) 
					     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
					     << 0xaU) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
			      | ((0x200U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						   << 3U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						     << 4U) 
						    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						    << 5U) 
						   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						   << 6U) 
						  & (IData)(vlTOPp->fx68k__DOT__ftu))) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						  << 7U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						 << 8U) 
						& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						<< 9U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
				 | ((0x100U & (((((
						   ((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						      << 2U) 
						     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
						    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							<< 3U) 
						       & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
						   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						       << 4U) 
						      & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						      << 5U) 
						     & (IData)(vlTOPp->fx68k__DOT__ftu))) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						     << 6U) 
						    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						    << 7U) 
						   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						   << 8U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
				    | ((0x80U & (((
						   ((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							<< 1U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
						      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							  << 2U) 
							 & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
						     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							 << 3U) 
							& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
						    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							<< 4U) 
						       & (IData)(vlTOPp->fx68k__DOT__ftu))) 
						   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						       << 5U) 
						      & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						      << 6U) 
						     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						     << 7U) 
						    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
				       | ((0x40U & 
					   ((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						     << 1U) 
						    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						    << 2U) 
						   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						   << 3U) 
						  & (IData)(vlTOPp->fx68k__DOT__ftu))) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						  << 4U) 
						 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						 << 5U) 
						& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
						<< 6U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))) 
					  | ((0x20U 
					      & (((((((0x7fffffe0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							   >> 1U) 
							  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL))) 
						      | (0xffffffe0U 
							 & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z)))) 
						     | (0xffffffe0U 
							& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							    << 1U) 
							   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z)))) 
						    | (0xffffffe0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							   << 2U) 
							  & (IData)(vlTOPp->fx68k__DOT__ftu)))) 
						   | (0xffffffe0U 
						      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							  << 3U) 
							 & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
						  | (0xffffffe0U 
						     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							 << 4U) 
							& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5)))) 
						 | (0xffffffe0U 
						    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							<< 5U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl))))) 
					     | ((0x10U 
						 & (((((((0x3ffffff0U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							      >> 2U) 
							     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL))) 
							 | (0x7ffffff0U 
							    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								>> 1U) 
							       & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z)))) 
							| (0xfffffff0U 
							   & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							      & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z)))) 
						       | (0xfffffff0U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							      << 1U) 
							     & (IData)(vlTOPp->fx68k__DOT__ftu)))) 
						      | (0xfffffff0U 
							 & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							     << 2U) 
							    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
						     | (0xfffffff0U 
							& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							    << 3U) 
							   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5)))) 
						    | (0xfffffff0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							   << 4U) 
							  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl))))) 
						| ((8U 
						    & (((((((0x1ffffff8U 
							     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								 >> 3U) 
								& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL))) 
							    | (0x3ffffff8U 
							       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								   >> 2U) 
								  & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z)))) 
							   | (0x7ffffff8U 
							      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								  >> 1U) 
								 & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z)))) 
							  | (0xfffffff8U 
							     & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								& (IData)(vlTOPp->fx68k__DOT__ftu)))) 
							 | (0xfffffff8U 
							    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								<< 1U) 
							       & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
							| (0xfffffff8U 
							   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							       << 2U) 
							      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5)))) 
						       | (0xfffffff8U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
							      << 3U) 
							     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl))))) 
						   | ((4U 
						       & (((((((0xffffffcU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								    >> 4U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL))) 
							       | (0x1ffffffcU 
								  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								      >> 3U) 
								     & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z)))) 
							      | (0x3ffffffcU 
								 & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								     >> 2U) 
								    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z)))) 
							     | (0x7ffffffcU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								    >> 1U) 
								   & (IData)(vlTOPp->fx68k__DOT__ftu)))) 
							    | (0xfffffffcU 
							       & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								  & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
							   | (0xfffffffcU 
							      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								  << 1U) 
								 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5)))) 
							  | (0xfffffffcU 
							     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								 << 2U) 
								& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl))))) 
						      | ((2U 
							  & (((((((0x7fffffeU 
								   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								       >> 5U) 
								      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL))) 
								  | (0xffffffeU 
								     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
									 >> 4U) 
									& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z)))) 
								 | (0x1ffffffeU 
								    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
									>> 3U) 
								       & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z)))) 
								| (0x3ffffffeU 
								   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								       >> 2U) 
								      & (IData)(vlTOPp->fx68k__DOT__ftu)))) 
							       | (0x7ffffffeU 
								  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								      >> 1U) 
								     & vlTOPp->fx68k__DOT__excUnit__DOT__auReg))) 
							      | (0xfffffffeU 
								 & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5)))) 
							     | (0xfffffffeU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								    << 1U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl))))) 
							 | (1U 
							    & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								      >> 6U) 
								     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__PcL)) 
								    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
									>> 5U) 
								       & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRx__05D_1348_24.z))) 
								   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								       >> 4U) 
								      & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__mux_regs68L__05BactualRy__05D_1349_24.z))) 
								  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								      >> 3U) 
								     & (IData)(vlTOPp->fx68k__DOT__ftu))) 
								 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								     >> 2U) 
								    & vlTOPp->fx68k__DOT__excUnit__DOT__auReg)) 
								| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								    >> 1U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__in_5))) 
							       | ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT____Vcellinp__mux_ablMux_1346_10__ctl) 
								  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__Atl)))))))))))))))))));
}

VL_INLINE_OPT void Vfx68k_fx68k_mux_1906::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_233_9__2(Vfx68k__Syms* __restrict vlSymsp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vfx68k_fx68k_mux_1906::_settle__TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_233_9__2\n"); );
    Vfx68k* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    this->z = ((0x8000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				  << 9U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				    << 0xaU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
			       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				   << 0xbU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
			      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				  << 0xcU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
			     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				 << 0xdU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
			    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				<< 0xeU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
			   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
			       << 0xfU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
	       | ((0x4000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				     << 8U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				       << 9U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
				  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				      << 0xaU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
				 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				     << 0xbU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
				| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				    << 0xcU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
			       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				   << 0xdU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
			      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				  << 0xeU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
		  | ((0x2000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					<< 7U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					  << 8U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
				     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					 << 9U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
				    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					<< 0xaU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
				   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				       << 0xbU) & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
				  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				      << 0xcU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
				 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
				     << 0xdU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
		     | ((0x1000U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					   << 6U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					     << 7U) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
					| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					    << 8U) 
					   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					   << 9U) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					  << 0xaU) 
					 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
				     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					 << 0xbU) & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
				    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					<< 0xcU) & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
			| ((0x800U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					     << 5U) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					       << 6U) 
					      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
					  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					      << 7U) 
					     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					     << 8U) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
					| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					    << 9U) 
					   & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
				       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					   << 0xaU) 
					  & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
				      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					  << 0xbU) 
					 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
			   | ((0x400U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						<< 4U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						  << 5U) 
						 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						 << 6U) 
						& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						<< 7U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
					   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					       << 8U) 
					      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
					  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					      << 9U) 
					     & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
					 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
					     << 0xaU) 
					    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
			      | ((0x200U & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						   << 3U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						     << 4U) 
						    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						    << 5U) 
						   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						   << 6U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						  << 7U) 
						 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						 << 8U) 
						& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						<< 9U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
				 | ((0x100U & (((((
						   ((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						      << 2U) 
						     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
						    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							<< 3U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
						   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						       << 4U) 
						      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						      << 5U) 
						     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						     << 6U) 
						    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						    << 7U) 
						   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						   << 8U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
				    | ((0x80U & (((
						   ((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							<< 1U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
						      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							  << 2U) 
							 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
						     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							 << 3U) 
							& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
						    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							<< 4U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
						   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						       << 5U) 
						      & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
						  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						      << 6U) 
						     & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						     << 7U) 
						    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
				       | ((0x40U & 
					   ((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
						 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						     << 1U) 
						    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
						| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						    << 2U) 
						   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
					       | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						   << 3U) 
						  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
					      | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						  << 4U) 
						 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
					     | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						 << 5U) 
						& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
					    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
						<< 6U) 
					       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))) 
					  | ((0x20U 
					      & (((((((0x7fffffe0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							   >> 1U) 
							  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z))) 
						      | (0xffffffe0U 
							 & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z)))) 
						     | (0xffffffe0U 
							& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							    << 1U) 
							   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z)))) 
						    | (0xffffffe0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							   << 2U) 
							  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3)))) 
						   | (0xffffffe0U 
						      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							  << 3U) 
							 & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z))) 
						  | (0xffffffe0U 
						     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							 << 4U) 
							& (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z)))) 
						 | (0xffffffe0U 
						    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							<< 5U) 
						       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch))))) 
					     | ((0x10U 
						 & (((((((0x3ffffff0U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							      >> 2U) 
							     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z))) 
							 | (0x7ffffff0U 
							    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								>> 1U) 
							       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z)))) 
							| (0xfffffff0U 
							   & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z)))) 
						       | (0xfffffff0U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							      << 1U) 
							     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3)))) 
						      | (0xfffffff0U 
							 & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							     << 2U) 
							    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z))) 
						     | (0xfffffff0U 
							& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							    << 3U) 
							   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z)))) 
						    | (0xfffffff0U 
						       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							   << 4U) 
							  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch))))) 
						| ((8U 
						    & (((((((0x1ffffff8U 
							     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								 >> 3U) 
								& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z))) 
							    | (0x3ffffff8U 
							       & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								   >> 2U) 
								  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z)))) 
							   | (0x7ffffff8U 
							      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								  >> 1U) 
								 & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z)))) 
							  | (0xfffffff8U 
							     & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3)))) 
							 | (0xfffffff8U 
							    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								<< 1U) 
							       & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z))) 
							| (0xfffffff8U 
							   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							       << 2U) 
							      & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z)))) 
						       | (0xfffffff8U 
							  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
							      << 3U) 
							     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch))))) 
						   | ((4U 
						       & (((((((0xffffffcU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								    >> 4U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z))) 
							       | (0x1ffffffcU 
								  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								      >> 3U) 
								     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z)))) 
							      | (0x3ffffffcU 
								 & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								     >> 2U) 
								    & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z)))) 
							     | (0x7ffffffcU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								    >> 1U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3)))) 
							    | (0xfffffffcU 
							       & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								  & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z))) 
							   | (0xfffffffcU 
							      & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								  << 1U) 
								 & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z)))) 
							  | (0xfffffffcU 
							     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								 << 2U) 
								& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch))))) 
						      | ((2U 
							  & (((((((0x7fffffeU 
								   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								       >> 5U) 
								      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z))) 
								  | (0xffffffeU 
								     & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
									 >> 4U) 
									& (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z)))) 
								 | (0x1ffffffeU 
								    & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
									>> 3U) 
								       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z)))) 
								| (0x3ffffffeU 
								   & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								       >> 2U) 
								      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3)))) 
							       | (0x7ffffffeU 
								  & (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								      >> 1U) 
								     & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z))) 
							      | (0xfffffffeU 
								 & ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								    & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z)))) 
							     | (0xfffffffeU 
								& (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								    << 1U) 
								   & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch))))) 
							 | (1U 
							    & (((((((((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								      >> 6U) 
								     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g21__Z)) 
								    | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
									>> 5U) 
								       & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g22__Z))) 
								   | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								       >> 4U) 
								      & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellout__g23__Z))) 
								  | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								      >> 3U) 
								     & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__in_3))) 
								 | (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								     >> 2U) 
								    & vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__shifter__DOT__mux_result_511_17.z)) 
								| (((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								    >> 1U) 
								   & (IData)(vlSymsp->TOP__fx68k__DOT__excUnit__DOT__alu__DOT__mux_result_276_8.z))) 
							       | ((IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT____Vcellinp__mux_result_233_9__ctl) 
								  & (IData)(vlTOPp->fx68k__DOT__excUnit__DOT__alu__DOT__bcdLatch)))))))))))))))))));
}

void Vfx68k_fx68k_mux_1906::_ctor_var_reset() {
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vfx68k_fx68k_mux_1906::_ctor_var_reset\n"); );
    // Body
    ctl = VL_RAND_RESET_I(7);
    in_0 = VL_RAND_RESET_I(16);
    in_1 = VL_RAND_RESET_I(16);
    in_2 = VL_RAND_RESET_I(16);
    in_3 = VL_RAND_RESET_I(16);
    in_4 = VL_RAND_RESET_I(16);
    in_5 = VL_RAND_RESET_I(16);
    in_6 = VL_RAND_RESET_I(16);
    z = VL_RAND_RESET_I(16);
}
